### ISSUE TITLE
Update application

### ISSUE THREAD

**Issue by lywly** [glichtner/pyeditorialmanager#1]
Hello there, I am not sure that whether you can continue to update this repository? it seems to raise some errors, but I cannot find out how to fix them.

**Comment by glichtner** [comment]
Hey, 
could you provide some information what exactly is not working?
Thanks

**Comment by lywly** [comment]
.overview() method seems to got Empty DataFrame, but actually I have several records on the website. 
"https://www.editorialmanager.com/advancedscience"
